

use DataTGDD

CREATE TABLE Accounts (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USERNAME NVARCHAR(50) UNIQUE,
    PASSWORD NVARCHAR(50)  NOT NULL,
    CREATEDDATE DATETIME NOT NULL,
    ROLE BIT NOT NULL,
    STATUS BIT NOT NULL
)

INSERT INTO Accounts (USERNAME, PASSWORD, CREATEDDATE, ROLE, STATUS)
VALUES ('johnsmith', 'password123', '2023-05-30', 1, 1);

INSERT INTO Accounts (USERNAME, PASSWORD, CREATEDDATE, ROLE, STATUS)
VALUES ('janedoe', 'abc123', '2023-05-31', 0, 1);

INSERT INTO Accounts (USERNAME, PASSWORD, CREATEDDATE, ROLE, STATUS)
VALUES ('admin', 'adminpass', '2023-06-01', 1, 1);

INSERT INTO Accounts (USERNAME, PASSWORD, CREATEDDATE, ROLE, STATUS)
VALUES ('admin3', 'adminpass', '2023-06-01', 1, 1);

select * from Accounts

DELETE FROM Accounts where ID=2;